spring:
  application:
    name: cards
  config:
    import: "optional:configserver:http://configserver:8083"
    #    import: "optional:configserver:http://localhost:8083"

server:
  port: 8090
  servlet:
    context-path: /cards-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "cards"
    description: "Eazy Bank Cards Application"
    version: "1.0.0"